name: grant_and_activate
description: Activate services and ask for associated permissions with a single method call.
version: 0.0.7
homepage: https://github.com/Alystrasz/grant_and_activate

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
  bluetooth_enable_fork: ^0.1.5
  flutter:
    sdk: flutter
  location: ^4.4.0
  permission_handler: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

