name: grant_and_activate
description: Manage services and associated permissions easily.
version: 0.0.1
homepage: https://github.com/Alystrasz/grant_and_activate

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
  bluetooth_enable: ^0.1.1
  flutter:
    sdk: flutter
  location: ^4.3.0
  permission_handler: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

