name: grant_and_activate
description: Activate services and ask for associated permissions with a single method call.
version: 0.0.5
homepage: https://github.com/Alystrasz/grant_and_activate

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
  bluetooth_enable: ^0.1.1
  flutter:
    sdk: flutter
  location: ^4.3.0
  permission_handler: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

